# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('id_referent', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processi',
            },
        ),
    ]
