# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantamarconi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processes',
            name='id_referent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
