# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantamarconi', '0002_auto_20171125_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processes',
            old_name='id_referent',
            new_name='referent',
        ),
    ]
