# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantamarconi', '0004_auto_20171204_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('surname', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('parent_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantamarconi.Organogram')),
            ],
        ),
    ]
