# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamarconi', '0005_organogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organogram',
            name='parent_level',
            field=models.IntegerField(),
        ),
    ]
