# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantamarconi', '0009_auto_20171208_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processes',
            name='referent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fantamarconi.Processes'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='referent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
