# Generated by Django 2.0 on 2017-12-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamarconi', '0010_auto_20171208_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='processes',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
