# Generated by Django 2.0 on 2017-12-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantamarconi', '0013_auto_20171214_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organogram',
            name='parent_level',
            field=models.ForeignKey(default='self', on_delete=django.db.models.deletion.PROTECT, to='fantamarconi.Organogram'),
        ),
    ]
