# Generated by Django 2.0 on 2017-12-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantamarconi', '0015_auto_20171214_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organogram',
            name='parent_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fantamarconi.Organogram'),
        ),
    ]
