# Generated by Django 2.0 on 2017-12-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantamarconi', '0016_auto_20171214_1514'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organogram',
            unique_together={('name', 'surname', 'email', 'sector', 'role', 'parent_level')},
        ),
    ]
