# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantamarconi', '0018_auto_20171214_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processes',
            name='slug',
        ),
    ]
