# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantamarconi', '0019_remove_processes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='processes',
            name='technical_referent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
